feature:
  - head-branch: ["^feat(ure)?/.*"]
feat:
  - head-branch: ["^feat(ure)?/.*"]

bug:
  - head-branch: ["^(fix|bugfix)/.*"]
fix:
  - head-branch: ["^(fix|bugfix)/.*"]

chore:
  - head-branch: ["^chore/.*"]
ci:
  - head-branch: ["^ci/.*"]
refactor:
  - head-branch: ["^refactor/.*"]

documentation:
  - head-branch: ["^docs?/.*"]

dependencies:
  - head-branch: ["^(deps?|dependabot)/.*"]
